server:
  port: 8080
spring:
  cloud: 
   gateway: 
    routes:
      - id: catalog
        uri: http://localhost:7777/
        predicates:
          - Path=/product/**
      - id: cart
        uri: http://localhost:8888/
        predicates:
          - Path=/cart/**
